### ISSUE TITLE
Why is there OnButtonPress and OnButtonEvent

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_core#101]
It looks like the only difference is eventMode vs pressMode where the values are UP/DOWN vs. LONG/SHORT. This could easily be one RPC.

**Comment by idamaster** [comment]
Very much by design, and mimics nearly every single keyboard or button API that is in existence. One notification serves as a way to determine the edges of the press (up/down), and the other serves as a way to determine if the key is stuck or not (long/short). 

Happy to discuss how this could be changed...

**Comment by justinjdickow** [comment]
Got it.
