### ISSUE TITLE
Add a default response for startH264

### ISSUE THREAD

**Issue by henry-fan** [smartdevicelink/sdl_core#11]
add a default response to notify the mobile app to start encoding video stream.

**Comment by justinjdickow** [comment]
@henry-fan Could you please give some context for this issue and what behavior is required?

**Comment by henry-fan** [comment]
![starth264 sequence chart](https://cloud.githubusercontent.com/assets/9698851/6016999/31b49984-abc4-11e4-80a9-438be468c292.png)

**Comment by lea255ace** [comment]
The video encoder on the mobile side is on our critical path. The decision to start sending video immediately after the StartH264 message rather than waiting until receiving a response from SDL core serves to hide some of the encoder latency.
In the case of a failed connection, the NACK from SDL core will cause the mobile to close down the connection.
