### ISSUE TITLE
CCB: fix updating consumer_friendly_messages

### ISSUE THREAD

**Issue by KhrystynaDubovyk** [smartdevicelink/sdl_core#1222]
### Bug Report
SDL updates `messages` section partially during PTU

##### Reproduction Steps
1. Make sure SDL is built with `HTTP` flow
2. Register new application => PTU is triggered
3. Send SystemRequest with specific PTU file (messages in UTF-8 format)
4. Check `consumer_friendly_messages.messages` in Policy database

##### Expected Behavior
SDL updates `consumer_friendly_messages.messages` section.

##### Observed Behavior
SDL just insert rows with empty `tts, label, line1, line2` and `textBody` fields.

##### OS & Version Information
* OS/Version: Ubuntu 16.04
* SDL Core Version: [develop](https://github.com/smartdevicelink/sdl_core/commit/d36316738785c96dab2ee892762ed08c059fffde)
* Testing Against: ATF

**Comment by jacobkeeler** [comment]
@KhrystynaDubovyk Does this only occur with the "HTTP" mode?

**Comment by LitvinenkoIra** [comment]
Priority Medium.
Loss of functionality in non-standard use case.

**Comment by LitvinenkoIra** [comment]
According to the description in https://github.com/smartdevicelink/sdl_core/pull/2295 - to reproduce this issue use the following ATF test script - 
ATF script: [083_ATF_PTU_UTF8_Encoding_Check_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/083_ATF_PTU_UTF8_Encoding_Check_HTTP.lua)

**Comment by LitvinenkoIra** [comment]
[083_ATF_PTU_UTF8_Encoding_Check_HTTP](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/develop/test_scripts/Policies/build_options/083_ATF_PTU_UTF8_Encoding_Check_HTTP.lua) - successfully passed on the latest develop (e1375565)
**Defect is not reproducible** because this issue was fixed in https://github.com/smartdevicelink/sdl_core/pull/2783/commits/2c83332223342252286f7d33520b83070259ef20 and was merged into develop as a part of [Feature/SDL passenger mode](https://github.com/smartdevicelink/sdl_core/pull/2783)
