### ISSUE TITLE
SDL doesn't change state of app when OnAppDeactivated("DeactivateReason") is sent

### ISSUE THREAD

**Issue by tayloead** [smartdevicelink/sdl_core#1243]
Based on the "Deactivate Reason", the OnHMIStatus Notification is supposed to change and send a certain response. However, the OnHMIStatus does not change for any "Deactivate Reason", everything stays as LIMITED and AUDIBLE.

**Comment by LitvinenkoIra** [comment]
Application may be deactivated due to several contitions:
 - other application activated
 - Radio activated
 - Navigation activated 
 - info button presed 
 - etc ... 

Based on deactivation reason different types of applications (NAVi or medi or voice communication) should be moved to different HMI levels.
For example if Navigation application(app1) of FULL and some other MEDIA application(app2) was activated. App1 should be moved to LIMITED state.  But if other NAVI application (app3) activated. app1 should be moved to background. This behavior is currently observed on SDL
