### ISSUE TITLE
Documentation for changing SDL server endpoint.

### ISSUE THREAD

**Issue by ssmereka** [smartdevicelink/sdl_core#126]
In order to connect core to an SDL server you must update the default policy JSON file or current mysql policy table database to point to the desired SDL server.  Documentation to do this does not currently exist on github, but should!

**Comment by ssmereka** [comment]
This issue is currently blocked by issue #127.

**Comment by justinjdickow** [comment]
Added a [policy wiki page](https://github.com/smartdevicelink/sdl_core/wiki/Policies) which addresses this documentation issue.

For convenience the answer is:

SDL uses the 0x07 endpoint defined in the [preloaded policy table](https://github.com/smartdevicelink/sdl_core/blob/develop/src/appMain/sdl_preloaded_pt.json#L16). This endpoint should be changed so that policy table triggers are directed to your own implementation of the SDL Server.

If SDL has already been run and the database has already been created, it should be removed and re-run (build/src/appMain/storage/policy.sqlite) or the database can be edited directly.
