### ISSUE TITLE
Core sending back null for properties in responses and notifications

### ISSUE THREAD

**Issue by asm09fsu** [smartdevicelink/sdl_core#1345]
We are currently having instances from mobile partners saying that they are receiving crashes when accessing the `buttonCapabilities` parameters of the `RegisterAppInterfaceResponse` object. It appears that they are attempting to access a null object, which can only be created if the iOS library receives `null` for that parameter. 

I have validated using core+sdl_hmi that if you send back `null` for `buttonCapabilities` by modifying the HMI, we do infact get a crash on the mobile side, so I am fairly confident that we know that this is the culprit.

We are trying to investigate the root causes of this issue. We have seen in the past that `OnTouchEvent` had a null timestamp if the GPS data was unobtainable, however that is resolved, and I'm not sure if this was a Core issue, HMI issue, or OEM issue.

@JackLivio or @jacobkeeler can you please investigate this issue, and if it is only on parameters that are arrays, or if there is a possibility for core to send back `null` for any array? Does core check if the HMI is infact sending the correct information (in this instance, a null vs an actual object)?

**Comment by JackLivio** [comment]
Sounds like somebody improperly configured the hmi_capabilities.json

If there are no hard buttons on a head unit they should be setting the button capabilities to
```
buttonCapabilities : []
```
or not including buttonCapabilities at all since its not a mandatory field in the register app interface response.

The only way that core could send 
```
buttonCapabilities : null
```
is if the integrator set that specifically to null in the hmi_capabilities.json, which is incorrect on their end.
