### ISSUE TITLE
Regarding update to HMI documentation

### ISSUE THREAD

**Issue by VGunasekaranHarman** [smartdevicelink/sdl_core#1813]
Hi,
Have downloaded the HMI documentation from the link - https://d83tozu1c8tt6.cloudfront.net/media/builds/pdf/hmi-documentation-english-e91a369a.pdf

Have been taken to this link from https://smartdevicelink.com/resources/pdfs/

It looks that all the HMI RPCs are not defined in the HMI documentation. For eg, OnEventChanged

Please provide the updated document.

Thanks.

**Comment by jacobkeeler** [comment]
I'm not certain what is covered by the document you linked, but you can find the HMI Integration Documentation (including RPCs) [here](https://smartdevicelink.com/en/docs/hmi/master/overview/) on the developer portal

Questions like this are best kept to the Slack group. In addition this is not SDL Core related. please post in the appropriate channel on [Slack](http://slack.smartdevicelink.com/).

**Comment by joeygrover** [comment]
@VGunasekaranHarman since this is specific to the HMI documentation, in the future please raise these issues in the documentation repo. Found here: https://github.com/smartdevicelink/sdl_hmi_integration_guidelines

I have already raised an issue for this specific missing RPC [here](https://github.com/smartdevicelink/sdl_hmi_integration_guidelines/issues/82).
