### ISSUE TITLE
building on Qt. Error in src/component/dbus/CmakeLists.txt line #77 

### ISSUE THREAD

**Issue by shadowQ5** [smartdevicelink/sdl_core#1824]
**How to reproduce**
 cmake -DHMI=qt -DHMI2=ON ../path/to/sdl/

**Fix entry**
add_dependecnies -> add_dependencies

**Comment by jacobkeeler** [comment]
This issue is known, a fix was submitted (#1730), but the fact is that the QT HMI hasn't been supported in several years. I intend on writing a [SDL Evolution](https://github.com/smartdevicelink/sdl_evolution) proposal in the near future to figure out how the SDLC would like to move forward with the QT HMI.

**Comment by jacobkeeler** [comment]
DBUS build will be fixed in the next release (https://github.com/smartdevicelink/sdl_core/pull/2005), but the `-DHMI=qt` option will no longer be available (https://github.com/smartdevicelink/sdl_core/issues/1857).
