### ISSUE TITLE
[SDL 0110] Remove QT HMI from SDL Core

### ISSUE THREAD

**Issue by theresalech** [smartdevicelink/sdl_core#1857]
Proposal: [Remove QT HMI from SDL Core](https://github.com/smartdevicelink/sdl_evolution/blob/master/proposals/0110-remove-qt-hmi-from-sdl-core.md)

> This proposal is for the removal of the QT HMI from the SDL Core repository.

Review: https://github.com/smartdevicelink/sdl_evolution/issues/335

Steering Committee Decision:

> The Steering Committee voted to accept this proposal, thereby agreeing to remove the QT HMI from SDL Core. They agreed that if desired, a proposal can be entered to discuss adding a QT HMI outside of the SDL Core repository, as another HMI.

**Comment by jacobkeeler** [comment]
The first task of this proposal has been merged with #1998.

The tasks remaining are:
- Remove QT_HMI_API, as well as any RPCs specific to this API (breaking changes, must be included as part of 5.0.0)
- Remove DBus library and adapter, or refactor it to use the regular HMI API (if necessary).

**Comment by chinlin0924** [comment]
hi @jacobkeeler , I saw you fix some dbus compiler error. since the SDL 0110 is accepted, why fix the DBUS issue? or any different decision is made?
thanks

**Comment by jacobkeeler** [comment]
@chinlin0924 To my understanding, we are considering the removal of the QT_HMI_API adapter to be a breaking change (due to it containing several RPCs which aren't present in the `HMI_API`, mainly just individual vehicle data RPCs), meaning it needs to be delayed until the next major release. The DBus adapter is the only one that uses this API at this time. 

In addition, after the proposal was accepted, we put out a question to the SDLC whether or not any of the members relied on the presence of the DBus adapter (since it's removal was implicit given the proposal), and we were not given a definitive answer at the time, so we went with a safe alternative of bringing it to at least to a buildable state for the coming release.

I suspect that we will ultimately end up removing this adapter, but as stated before, it will need to be done in the `5.0.0` release.

**Comment by jacobkeeler** [comment]
Closing with the merge of #2330
