### ISSUE TITLE
UnSubscribeWayPoints RPC - Unwanted parameter referenced

### ISSUE THREAD

**Issue by robinmk** [smartdevicelink/sdl_core#2267]
### Bug Report
In the current version of MOBILE_API.xml, the `UnsubscribeWayPoints` RPC includes the following parameter which is not required in that RPC:
` <param name="wayPoints" type="LocationDetails" mandatory="false" array="true" minsize="1" maxsize="10">`

##### Expected Behavior
This parameter is not expected in the `UnsubscribeWayPoints` RPC as the wayPoints details are provided via the `OnWayPointChange` RPC.
This appears to be an error in the documentation.

**Comment by jacobkeeler** [comment]
Mobile API issues should be submitted to https://github.com/smartdevicelink/rpc_spec, now that the Mobile API in Core is based off of this. I also must mention that deprecating/removing this parameter would require a evolution proposal at this point. This might not be worth it in this case, since it is a non-mandatory parameter which can be safely ignored by the proxy in any case.
