### ISSUE TITLE
HMI sends request with wrong json syntax

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2352]
### Bug Report
HMI sends request with wrong json syntax.

##### Reproduction Steps
1. HMI sends *request to SDL (please see list of impacted RPCs below) and this request has wrong json syntax.

##### Expected Behavior
Log corresponding error internally respond with 'INVALID_DATA' to HMI.

##### OS & Version Information
* OS/Version:
* SDL Core Version:
* Testing Against:

**Comment by ZhdanovP** [comment]
Request was created for F-S and then moved to Sync4.
Request wasn't implemented due to logical impossibility.

Wrong json cannot be parsed by SDL. So, SDL has no information about incoming request (session id, id etc) , so it is impossible to send INVALID_DATA to unknown request.

The time when CRQ was implemented, this particular requirement was not implemented by this reason.
So, task was created by mistake. Such functionality is absent in F-S SDL and Sync4 also.

Closed because nothing to do in this ticket.
