### ISSUE TITLE
Increase unit tests coverage

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2449]
### Bug Report
Need  to increase unit tests coverage 

- Add Unit tests to cover changes in Session and Policy Handler 

- Modified Policy Handler Unit tests.

- Add Unit tests for Connection Handler.

- Add Unit tests for RPC Service.

- Add Unit tests for CacheManager.

##### OS & Version Information
* OS/Version: Ubutnu 18
* SDL Core Version: 6.0

**Comment by JackLivio** [comment]
RPC Service unit tests merged in #3250

**Comment by JackLivio** [comment]
@HSavynetska @ychernysheva Are there planned prs for application manager and connection UT coverage?

Also I would like to split this issue into separate issues in order to keep 1 issue to 1 pr.

**Comment by ychernysheva** [comment]
@JackLivio Now we don't have any new PRs with unit tests for Application Manager or Connection. In the case of Connection coverage is large enough (95,5/100 % by lines/functions), that's why it seems that there is no need in new tests.

In the case of Application Manager coverage is not enough (42.4/42.8 %), but major part of complex methods is covered, that's why it seems, that this task may have relatively low priority (but if you think that it's important, we can create a new issue for this).

Also I've deleted mentions to Application Manager and Connection from description of this issue, so it may be closed after merging of remaining PR with unit tests for Connection handler and Policy handler.
