### ISSUE TITLE
SDL does not  remove app from waypoints list 

### ISSUE THREAD

**Issue by HSavynetska** [smartdevicelink/sdl_core#2461]
### Bug Report
SDL does not  remove app from waypoints list 

##### Reproduction Steps
1. In case of expected disconnect SDL never removes the app
from subscribe way points list. As a result during next connection SDL
does not send SubscribeWayPoits request to HMI.

##### Expected Behavior
SDL remove app from waypoints list 

##### Observed Behavior
SDL does not  remove app from waypoints list 

##### OS & Version Information
* OS/Version:
* SDL Core Version: 
* Testing Against:

**Comment by E-SAITO-TMC** [comment]
@theresalech -san This issue is a medium priority for Toyota. The fix for this issue seems to have already been merged, is this issue resolved? If not, I would like to know if it will occur in the latest version. Also, could you please include this issue in your plan? Thank you.

**Comment by theresalech** [comment]
Hi @E-SAITO-TMC, we have documented that this is medium priority for Toyota, and will include for Steering Committee review and vote when planning the contents for the Q4 Core release. The PR you referenced was not merged into the mainline, which is why the issue has not yet been closed.  We will need more information from the reporter in order to determine next steps.

@HSavynetska, can you please advise if you are seeing this issue when using Core 6.1?

**Comment by dboltovskyi** [comment]
@theresalech Please notice issue is still actual for Core 6.1

**Comment by iCollin** [comment]
Closed via https://github.com/smartdevicelink/sdl_core/pull/3373
