### ISSUE TITLE
SDL sends INVALID_DATA and GENERIC_ERROR  responses instead of SUCCESS in case Mobile App sends SystemRequest (ICON_URL) with binary data

### ISSUE THREAD

**Issue by VjKlepikov** [smartdevicelink/sdl_core#2873]
### Bug Report
SDL sends INVALID_DATA and GENERIC_ERROR responses instead of SUCCESS in case Mobile App sends SystemRequest (ICON_URL) with binary data

Precondition:
  1. Cloud App in the policy table
  2. HMI and SDL are started
  3. Mobile App is registered and activated

##### Reproduction Steps
1. Send SystemRequest (ICON_URL) with binary data to SDL from Mobile App

##### Expected Behavior
1. SDL sends successful response to Mobile App

##### Observed Behavior
1. SDL sends INVALID_DATA and GENERIC_ERROR  responses to Mobile App

##### OS & Version Information
* OS/Version: [16.04]
* Mobile app: Android 5.0.2
* Mobile device: Samsung SM-G530H
* Mobile Apps: SPT(20190122)
* Transport: BT
* SDL Core Version: [5.1.0] [b9500e5](https://github.com/smartdevicelink/sdl_core/commit/b9500e5e6f1c39db7eaee3a7416179edf0ac5dc6)

##### Test Case, Sample Code, and / or Example App
[SDL_log.zip](https://github.com/smartdevicelink/sdl_core/files/3038392/SDL_log.zip)

**Comment by jacobkeeler** [comment]
This request type should not be used without a corresponding `OnSystemRequest` of `ICON_URL` type sent by Core to that application. 

In your logs, I see that an `OnSystemRequest(ICON_URL)` with a url of `https://noiconurl.org` is sent by Core, but the fileName sent in the `SystemRequest(ICON_URL)` is `icon.png`. 

This parameter needs to be filled with the original url sent in the `OnSystemRequest(ICON_URL)`, because multiple `OnSystemRequest(ICON_URL)` notifications can be sent in a session, and without the original URL it is not possible for Core to differentiate these requests.

**Comment by jacobkeeler** [comment]
It appears that the extra GENERIC_ERROR response is just because of a missing return after the INVALID_DATA response, will submit a fix for this.

**Comment by dboltovskyi** [comment]
@theresalech Please triage this issue

**Comment by jacobkeeler** [comment]
Closing with the merge of #2875
