### ISSUE TITLE
CCB: HMI status of Apps are not set properly

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3165]
### Bug Report
HMI status of Apps are not set Properly

### Detailed analysis:
OnHMIStatus status is not handled properly between the media application and the media projection. The HMI status changes from BACKGROUND to NONE when the SDL receives OnEventChanged with AudioSource: True, and also there are no checks to differentiate between apps that are dependent on AudioSource.

##### Reproduction Steps
1. Launch the SPT App
2. Check the HMI status of SPT on the phone (it should be in FULL)
3. Go to in-app menu and press 'Exit SPT'
4. Check the HMI status of SPT on the phone

##### Expected Behavior
HMI status of SPT on the phone should be in NONE as the app has been exited

##### Observed Behavior
HMI status of SPT on the phone changes to NONE for 2 seconds and moves to BACKGROUND even though the app has been exited

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by Ypostolov** [comment]
The issue is not relevant on the current develop branch.
The current implementation of the  Smartdevicelink/sdl_core is different from the implementation of  SYNC/sdl_core for which was opened issue.
Environment:
Test script: https://github.com/smartdevicelink/sdl_atf_test_scripts/pull/2324
SDL build: https://github.com/smartdevicelink/sdl_core/tree/develop (49f5b211ca995193d68301b0b3c08e3df427568f)
ATF: develop branch
