### ISSUE TITLE
CCB: Fix mutex deadlock while certificate update required 

### ISSUE THREAD

**Issue by LitvinenkoIra** [smartdevicelink/sdl_core#3177]
### Bug Report
Mutex deadlock while certificate update required 

### Detailed analysis:
This deadlock happens when SecurityManager from one thread notifies listeners that certificate
update is required and in another thread after PTU finish, OnCertificateUpdated callback is called in SecurityManager.
First thread holds policy_manager_lock_ and the second one holds waiters_lock_ in   SecurityManagerImpl::StartHandshake and as a result - deadlock.

##### Reproduction Steps
1. TBD

##### Expected Behavior
SDL should not crash

##### Observed Behavior
SDL crashed

#### OS & Version Information
* OS/Version : SYNC4
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/releases/tag/5.0.1 
* Testing Against: SYNC4 Applink

**Comment by AKalinich-Luxoft** [comment]
Fix is not actual for OpenSDL: Such deadlock is not possible in OpenSDL as for access to `policy_manager_` instance SDL is using RWLock in read mode in both threads. RWLock allows multiple readers to have an access to the same resource, that's why in this scenario mentioned thread will not be in a conflict.
