### ISSUE TITLE
Redundant OnPermissionsChange notification during app registration

### ISSUE THREAD

**Issue by GetmanetsIrina** [smartdevicelink/sdl_core#3234]
### Bug Report
Redundant OnPermissionsChange notification during app registration on external policy flow

##### Occurrences
Sometimes

##### Precondition
1. SDL is built with EXTERNAL_PROPRIETARY policy flow
2. HMI and SDL are started 
3. Mobile device is allowed

##### Reproduction Steps
1. Register app

##### Expected Behavior
SDL sends one OnPermissionsChange notification to mobile app

##### Observed Behavior
SDL sends two OnPermissionsChange notifications to mobile app

##### OS & Version Information
* OS/Version: Ubuntu 18.04
* SDL Core Version: https://github.com/smartdevicelink/sdl_core/commit/fcdacd760c6182e73f3517b3baa0dd10660ff0e8
* ATF: develop
* Script: TBA

##### Logs
[ATF_and_SDL_logs.zip](https://github.com/smartdevicelink/sdl_core/files/4164672/ATF_and_SDL_logs.zip)

**Comment by dboltovskyi** [comment]
Issue is related to the fact that app is registered right after SDL got `SDL.OnAllowSDLFunctionality` notification from HMI.
Since this is a notification and not request, SDL requires some time to change state for connected device.
Most of the new scripts has a delay after this notification, (e.g. in [mobile.allowSDL](https://github.com/smartdevicelink/sdl_atf_test_scripts/blob/49804a37513a56b25c6fec84d41cff132cf40671/user_modules/sequences/actions.lua#L362) )
So I would propose to close the issue.
