### ISSUE TITLE
libssl-dev and libudev-dev are not caught by cmake

### ISSUE THREAD

**Issue by justinjdickow** [smartdevicelink/sdl_core#601]
cmake should fail if these libraries are not installed.

**Comment by jacobkeeler** [comment]
It looks like this can be easily fixed by adding find_package() commands in the main CMakeLists.txt where necessary. 

We need an extra module to detect udev, but I was quickly able to find a cmake script for it [here](https://github.com/FreeRDP/FreeRDP/blob/master/cmake/FindUDev.cmake). 

libudev-dev should only be necessary when usb support is enabled from what I can tell, though it looks like libssl-dev is necessary as a general dependency.

Submitting a PR...
