### ISSUE TITLE
PerformAudioPassThru Delayed Notifications

### ISSUE THREAD

**Issue by tayloead** [smartdevicelink/sdl_core#835]
There seems to be an issue where a message isn't occurring at a rate we see on Sync 3. Whenever the performaudiopassthru message is sent from the phone to the sync3 emulator, I am receiving performaudiopassthru notifications, going to sdl_core back to the phone, at a rate of about one notification per 5 seconds, compared to receiving these notifications once every .05 seconds when testing with the actual sync module.

I believe these notifications are from the audio capturing/streaming

**Comment by jacobkeeler** [comment]
@tayloead It looks like the reason behind why these notifications take so long to appear is because of:

1. Each individual "OnAudioPassThru" message contains significantly more data when sent from the current version of SDL Core compared to the TDK, resulting in larger and more spaced-out notifications.
2. It also appears that the current version of SDL Core sends an audio file that is significantly larger than what is sent from the TDK (~1.5MB vs ~300KB), likely due to difference in sampling rates. As a result, the Bluetooth transport is simply not able to transfer that amount of data quickly enough due to [the limitations of SPP](http://stackoverflow.com/questions/32091614/bluetooth-spp-throughput).

The only real way around this issue would be to reduce the sampling rate of the audio sent from SDL Core, however it does not appear as if SDL Core actually takes into account the "samplingRate" or "bitsPerSample" fields when recording the audio.
